# Assigment 1 
## Neural Networks Lab

In [1]:
import numpy as np

# Q1:
+ sigmoid fn and its gradient.

In [2]:
def sigmoid(x, derivative=False):
    # gradient of sigmoid func.
    if derivative == True:
        return x * (1 - x)
    # sigmoid fn 
    return 1.0 / (1 + (np.exp(-x)))

In [3]:
# get array of random 3 elements
x = np.array(np.random.randint(1,10,3))
print(x)
# use gradient of sigmoid func
sigmoid(x)

[3 1 6]


array([ 0.95257413,  0.73105858,  0.99752738])

In [4]:
# get array of random 3 elements
x = np.array(np.random.randint(1,10,3))
print(x)
# use sigmoid fn 
sigmoid(x, derivative=True)

[6 1 7]


array([-30,   0, -42])

# Q2:
+ Image2vector fn.

In [5]:
def image2vector(img):
    # reshape by (length*height*depth, 1) means many rows and only one column
    return img.reshape(img.shape[0]*img.shape[1]*img.shape[2],1)

In [6]:
# make a 3D array as image
img = np.ones((2,2,3))
print(img)
image2vector(img)

[[[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]


array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])

# Q3:
+ Normalize matrix rows fn

In [7]:
def normalizeRows(x):
    x_norm = np.linalg.norm(x, axis = 1, keepdims = True)
    return x / x_norm

In [8]:
x = np.array(np.random.randint(0,9,6).reshape(2,3))
print(x)
normalizeRows(x)

[[5 1 6]
 [3 1 4]]


array([[ 0.63500064,  0.12700013,  0.76200076],
       [ 0.58834841,  0.19611614,  0.78446454]])

# Q4:
+ L1 and L2 loss fns

In [9]:
def loseFunc1(predicted, truth):
    # the sum of the absolute values of the difference of 2 vectors
    return sum(abs(truth - predicted))

In [10]:
predicted = np.array(np.random.randint(0,10,5))
print("predicted values",predicted)
truth = np.array(np.arange(0,5))
print("truth values",truth)
loseFunc1(predicted, truth)

predicted values [3 8 7 3 3]
truth values [0 1 2 3 4]


16

In [11]:
def loseFunc2(predicted, truth):
    # the sum of the squared difference of 2 vectors
    return sum((truth - predicted)**2)

In [12]:
predicted = np.array(np.random.randint(0,10,5))
print("predicted values",predicted)
truth = np.array(np.arange(0,5))
print("truth values",truth)
loseFunc2(predicted, truth)

predicted values [1 7 0 4 5]
truth values [0 1 2 3 4]


43